services:
  asapbi-postgres:
    image: postgres:15-alpine
    container_name: asapbi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    labels:
      asapbi.connection.instance_name: "GREENPLUM"      # customer label! need for asapBI
      asapbi.connection.type: "PostgreSQL"              # customer label! need for asapBI 
      asapbi.connection.port: "15432"                   # customer label! need for asapBI
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/postgresql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - asapbi-net

  asapbi-clickhouse:
    image: clickhouse/clickhouse-server:24.8-alpine
    container_name: asapbi-clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DB: analytics
    ports:
      - "18123:8123"   # HTTP
      - "19000:9000"   # Native
    labels:
      asapbi.connection.instance_name: "CLICKHOUSE"   # customer label! need for asapBI
      asapbi.connection.type: "Clickhouse"            # customer label! need for asapBI
      asapbi.connection.port: "18123"                 # customer label! need for asapBI
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      - ./init/clickhouse:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - asapbi-net

  asapbi-cube:
    build: ./cube-api # Путь к вашей новой папке с Dockerfile
    container_name: asapbi-cube
    restart: unless-stopped
    ports:
      - "4000:4000"   # Cube API
      - "15433:5432"  # SQL API (для Superset)
      - "8000:8000"   # Ваш Python API для загрузки схем
    environment:
      - CUBEJS_DB_TYPE=clickhouse
      - CUBEJS_DB_HOST=asapbi-clickhouse
      - CUBEJS_DB_NAME=analytics
      - CUBEJS_DB_USER=admin
      - CUBEJS_DB_PASS=admin
      - CUBEJS_API_SECRET=asapbi_secret_key_999
      - CUBEJS_SQL_PORT=5432
      - CUBEJS_DEV_MODE=true
    volumes:
      - ./cube-model:/cube/conf/model
    networks:
      - asapbi-net

volumes:
  postgres-data:
    driver: local
  clickhouse-data:
    driver: local
  clickhouse-logs:
    driver: local

networks:
  asapbi-net:
    driver: bridge